import{BadRequestException,Body,Controller,Get,ParseIntPipe,Post,Query,StreamableFile,UploadedFile,UseGuards,UseInterceptors}from'@nestjs/common';import{FileInterceptor}from'@nestjs/platform-express';import{AccountType}from'@prisma/client';import{IsString}from'class-validator';import{JwtAuthGuard}from'../auth/jwt-auth.guard';import{AuthUser}from'../auth/jwt.strategy';import{CurrentUser}from'../common/current-user.decorator';import{PrismaService}from'../prisma/prisma.service';import{ProviderGateway}from'./provider.gateway';
interface UploadFile{buffer:Buffer;mimetype:string;size:number}
class GeocodeDto{@IsString()address!:string;@IsString()city!:string}
@Controller('demo')export class DemoProvidersController{constructor(private readonly providers:ProviderGateway,private readonly prisma:PrismaService){}
 @Post('storage/upload')@UseInterceptors(FileInterceptor('file',{limits:{fileSize:10_000_000}}))upload(@UploadedFile()file:UploadFile,@Query('key')key:string,@Query('mime')mime:string,@Query('expires',ParseIntPipe)expires:number,@Query('signature')signature:string){if(!file)throw new BadRequestException('file is required');return this.providers.store(key,mime||file.mimetype,expires,signature,file.buffer)}
 @Get('storage/download')async download(@Query('key')key:string,@Query('expires',ParseIntPipe)expires:number,@Query('signature')signature:string){return new StreamableFile(await this.providers.load(key,expires,signature))}
 @Post('maps/geocode')@UseGuards(JwtAuthGuard)geocode(@Body()d:GeocodeDto){return this.providers.geocode(d.address,d.city)}
 @Get('providers/status')@UseGuards(JwtAuthGuard)async status(@CurrentUser()u:AuthUser){if(u.accountType!==AccountType.ADMIN)throw new BadRequestException('Admin account required');const[outbox,events]=await Promise.all([this.prisma.notificationOutbox.groupBy({by:['channel','status'],_count:true}),this.prisma.providerEvent.findMany({orderBy:{createdAt:'desc'},take:50})]);return{mode:'demo',outbox,events}}
 @Get('outbox')@UseGuards(JwtAuthGuard)outbox(@CurrentUser()u:AuthUser){if(u.accountType!==AccountType.ADMIN)throw new BadRequestException('Admin account required');return this.prisma.notificationOutbox.findMany({orderBy:{createdAt:'desc'},take:100})}}
