import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common'; import { AccountType, BookingStatus, BusinessRole, DeliveryMethod, DeliveryStatus, Prisma } from '@prisma/client'; import { PrismaService } from '../prisma/prisma.service';
@Injectable() export class ExperienceService {
 constructor(private readonly p:PrismaService){}
 publicServices(category?:string,city?:string){return this.p.service.findMany({where:{active:true,business:{status:'ACTIVE',fiscalisation:{is:{status:{in:['COMPLIANT','EXPIRING_SOON']},taxClearanceExpiresAt:{gt:new Date()},deviceActive:true}},...(city?{branches:{some:{city:{equals:city,mode:'insensitive'}}}}:{})},...(category?{category:{equals:category,mode:'insensitive'}}:{})},select:{id:true,name:true,category:true,description:true,durationMinutes:true,price:true,currency:true,business:{select:{name:true,slug:true,verificationLevel:true}},bookings:{where:{startsAt:{gte:new Date()}},select:{startsAt:true,endsAt:true}}}})}
 async createService(userId:string,businessId:string,d:{name:string;category:string;description?:string;durationMinutes:number;price?:number;currency?:string}){await this.member(userId,businessId,[BusinessRole.OWNER,BusinessRole.MANAGER]);const business=await this.p.business.findUnique({where:{id:businessId},include:{fiscalisation:true}});if(!business||business.status!=='ACTIVE'||!['COMPLIANT','EXPIRING_SOON'].includes(business.fiscalisation?.status||''))throw new ForbiddenException('Services cannot be published until business compliance is approved');return this.p.service.create({data:{...d,businessId,price:d.price==null?undefined:new Prisma.Decimal(d.price),currency:d.currency?.toUpperCase()}})}
 async book(userId:string,type:string,serviceId:string,branchId:string|undefined,startsAt:Date,notes?:string){if(type!==AccountType.CUSTOMER)throw new ForbiddenException('Customer account required');const service=await this.p.service.findFirst({where:{id:serviceId,active:true,business:{status:'ACTIVE',fiscalisation:{is:{status:{in:['COMPLIANT','EXPIRING_SOON']},taxClearanceExpiresAt:{gt:new Date()},deviceActive:true}}}}});if(!service)throw new NotFoundException('Store temporarily unavailable while compliance is renewed');const endsAt=new Date(startsAt.getTime()+service.durationMinutes*60000);const clash=await this.p.booking.count({where:{serviceId,status:{in:['REQUESTED','CONFIRMED','IN_PROGRESS']},startsAt:{lt:endsAt},endsAt:{gt:startsAt}}});if(clash)throw new BadRequestException('Time slot is unavailable');return this.p.booking.create({data:{serviceId,customerId:userId,branchId,startsAt,endsAt,customerNotes:notes}})}
 async updateBooking(userId:string,businessId:string,id:string,status:BookingStatus){await this.member(userId,businessId);const booking=await this.p.booking.findFirst({where:{id,service:{businessId}}});if(!booking)throw new NotFoundException('Booking not found');return this.p.booking.update({where:{id},data:{status}})}
 async createDelivery(userId:string,businessId:string,orderId:string,d:{branchId?:string;method:DeliveryMethod;providerName?:string;recipientName:string;recipientPhone:string;address?:string;city:string;expectedAt?:Date}){await this.member(userId,businessId);const order=await this.p.withContext({userId},tx=>tx.order.findFirst({where:{id:orderId,businessId}}));if(!order)throw new NotFoundException('Order not found');return this.p.delivery.create({data:{...d,orderId,trackingCode:crypto.randomUUID()}})}
 track(code:string){return this.p.delivery.findUnique({where:{trackingCode:code},select:{trackingCode:true,status:true,method:true,providerName:true,city:true,expectedAt:true,deliveredAt:true}})}
 async deliveryStatus(userId:string,businessId:string,id:string,status:DeliveryStatus){await this.member(userId,businessId);return this.p.withContext({userId},async tx=>{const delivery=await tx.delivery.findFirst({where:{id,order:{businessId}}});if(!delivery)throw new NotFoundException('Delivery not found');return tx.delivery.update({where:{id},data:{status,deliveredAt:status==='DELIVERED'?new Date():undefined}})})}
 async review(userId:string,orderId:string,rating:number,comment?:string){const order=await this.p.withContext({userId},tx=>tx.order.findFirst({where:{id:orderId,customerId:userId,status:'DELIVERED'}}));if(!order)throw new BadRequestException('Only delivered purchases can be reviewed');return this.p.review.create({data:{orderId,customerId:userId,businessId:order.businessId,rating,comment}})}
 async dispute(userId:string,orderId:string,reason:string,details:string,evidence?:object){const order=await this.p.withContext({userId},tx=>tx.order.findFirst({where:{id:orderId,OR:[{customerId:userId},{business:{members:{some:{userId}}}}]}}));if(!order)throw new NotFoundException('Order not found');return this.p.dispute.create({data:{orderId,openedById:userId,reason,details,evidence}})}
 support(userId:string,d:{businessId?:string;category:string;subject:string;details:string;evidence?:object}){return this.p.supportTicket.create({data:{...d,userId}})}
 private async member(userId:string,businessId:string,roles?:BusinessRole[]){const m=await this.p.businessMember.findUnique({where:{userId_businessId:{userId,businessId}}});if(!m)throw new NotFoundException('Business not found');if(roles&&!roles.includes(m.role))throw new ForbiddenException('Insufficient permission');return m}
}
