'use client';
import Link from 'next/link';
import { FormEvent, useState } from 'react';
import { ArrowLeft, ArrowRight, Bell, Check, LoaderCircle, LockKeyhole, MapPin, ShieldCheck, ShoppingBag } from 'lucide-react';
import { api, saveSession, Session } from '../../../src/api';
import '../../login/login.css';
import './register-customer.css';

const provinces=['Bulawayo','Harare','Manicaland','Mashonaland Central','Mashonaland East','Mashonaland West','Masvingo','Matabeleland North','Matabeleland South','Midlands'];
const policies=['Terms and conditions','Privacy policy','Purchasing rules','Return and refund policy','Review and conduct rules'];

export default function CustomerRegistrationPage(){
  const [step,setStep]=useState<1|2|3>(1); const [session,setSession]=useState<Session|null>(null); const [code,setCode]=useState(''); const [devCode,setDevCode]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
  const [form,setForm]=useState({fullName:'',phone:'+263',email:'',password:'',province:'Harare',city:'',suburb:'',address:'',notificationPreference:'SMS'}); const [accepted,setAccepted]=useState<string[]>([]);
  const update=(key:keyof typeof form,value:string)=>setForm(current=>({...current,[key]:value}));
  async function register(event:FormEvent){event.preventDefault();if(accepted.length!==policies.length){setError('Please accept all marketplace policies to continue.');return;}setLoading(true);setError('');try{const created=await api.register({accountType:'CUSTOMER',fullName:form.fullName,phone:form.phone,email:form.email||undefined,password:form.password,province:form.province,city:form.city,suburb:form.suburb||undefined,notificationPreference:form.notificationPreference,deliveryAddress:{label:'Home',address:form.address,city:form.city,province:form.province,suburb:form.suburb||undefined},acceptedPolicies:true});setSession(created);const result=await api.requestVerification(created.accessToken,'PHONE');setDevCode(result.developmentCode||'');setStep(3);}catch(reason){setError(reason instanceof Error?reason.message:'Customer registration could not be completed.');}finally{setLoading(false)}}
  async function verify(event:FormEvent){event.preventDefault();if(!session)return;setLoading(true);setError('');try{await api.confirmVerification(session.accessToken,'PHONE',code);saveSession(session);window.location.href='/dashboard';}catch(reason){setError(reason instanceof Error?reason.message:'Verification failed.');}finally{setLoading(false)}}
  return <main className="customer-register-page"><aside className="customer-register-story"><Link className="login-brand" href="/"><span className="login-logo">Z</span><span>ZimMarket</span></Link><div><span>JOIN THE MARKET</span><h1>Everything local,<br/>made personal.</h1><p>Create a secure customer account to shop, book services, compare quotations and track every order.</p><ul><li><ShieldCheck/> Verified businesses</li><li><ShoppingBag/> Multi-shop marketplace</li><li><MapPin/> Delivery and collection choices</li><li><Bell/> Alerts you control</li></ul></div><small>Your sensitive details stay private and are shared only when needed to fulfil your request.</small></aside><section className="customer-register-main"><div className="customer-register-wrap"><Link className="back-home" href="/login/customer"><ArrowLeft/> Customer login</Link><div className="mobile-brand"><span className="login-logo">Z</span><span>ZimMarket</span></div><div className="register-progress"><span className={step>=1?'active':''}><i>{step>1?<Check/>:'1'}</i>Account</span><b/><span className={step>=2?'active':''}><i>{step>2?<Check/>:'2'}</i>Policies</span><b/><span className={step>=3?'active':''}><i>3</i>Verify</span></div>{step<3&&<><span className="form-kicker">CUSTOMER REGISTRATION</span><h2>{step===1?'Create your account':'Review and accept'}</h2><p className="form-intro">{step===1?'Your details help shops deliver and serve you correctly.':'These policies protect customers, businesses and the marketplace.'}</p></>}
  {step===1&&<form className="customer-details-form" onSubmit={e=>{e.preventDefault();setError('');setStep(2)}}><label className="wide">Full name<input value={form.fullName} onChange={e=>update('fullName',e.target.value)} minLength={2} required autoFocus/></label><label>Phone number<input value={form.phone} onChange={e=>update('phone',e.target.value)} required/></label><label>Email address<input type="email" value={form.email} onChange={e=>update('email',e.target.value)} required/></label><label>Province<select value={form.province} onChange={e=>update('province',e.target.value)}>{provinces.map(p=><option key={p}>{p}</option>)}</select></label><label>City or town<input value={form.city} onChange={e=>update('city',e.target.value)} minLength={2} required/></label><label>Suburb<input value={form.suburb} onChange={e=>update('suburb',e.target.value)}/></label><label>Preferred notifications<select value={form.notificationPreference} onChange={e=>update('notificationPreference',e.target.value)}><option value="SMS">SMS</option><option value="EMAIL">Email</option><option value="BOTH">Email and SMS</option><option value="NONE">Only in-app</option></select></label><label className="wide">Primary delivery address<textarea value={form.address} onChange={e=>update('address',e.target.value)} required rows={2} placeholder="House number, street and area"/></label><label className="wide">Password<input type="password" value={form.password} onChange={e=>update('password',e.target.value)} minLength={10} required placeholder="At least 10 characters"/></label>{error&&<div className="login-error wide">{error}</div>}<button className="login-submit wide">Continue to policies <ArrowRight/></button></form>}
  {step===2&&<form onSubmit={register}><div className="policy-list">{policies.map(policy=><label key={policy} className={accepted.includes(policy)?'accepted':''}><input type="checkbox" checked={accepted.includes(policy)} onChange={e=>setAccepted(current=>e.target.checked?[...current,policy]:current.filter(item=>item!==policy))}/><span><b>{policy}</b><small>Read and accept the current ZimMarket {policy.toLowerCase()}.</small></span><Check/></label>)}</div><p className="policy-record"><LockKeyhole/> Version 2026-08-23 and your acceptance date will be securely recorded.</p>{error&&<div className="login-error">{error}</div>}<div className="register-buttons"><button type="button" onClick={()=>setStep(1)}>Back</button><button className="login-submit" disabled={loading}>{loading?<><LoaderCircle className="spin"/> Creating account…</>:<>Accept and register <ArrowRight/></>}</button></div></form>}
  {step===3&&<div className="verification-step"><span><ShieldCheck/></span><h2>Verify your phone</h2><p>Enter the six-digit code sent to <b>{form.phone}</b>.</p>{devCode&&<div className="development-code">Development code: <b>{devCode}</b></div>}<form onSubmit={verify}><input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} inputMode="numeric" maxLength={6} placeholder="000000" autoFocus required/>{error&&<div className="login-error">{error}</div>}<button className="login-submit" disabled={loading||code.length!==6}>{loading?<LoaderCircle className="spin"/>:'Verify and open dashboard'} {!loading&&<ArrowRight/>}</button></form><button className="resend-code" onClick={async()=>{if(session){const result=await api.requestVerification(session.accessToken,'PHONE');setDevCode(result.developmentCode||'');}}}>Send another code</button></div>}</div></section></main>;
}
