import { BadRequestException, ForbiddenException, Injectable } from '@nestjs/common';
import { AccountType, AdStatus, BusinessStatus, DisputeStatus, DocumentStatus, PayoutStatus, ReportStatus, VerificationLevel } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
@Injectable() export class AdminService {
  constructor(private readonly prisma: PrismaService) {}
  assertAdmin(type: string) { if (type !== AccountType.ADMIN) throw new ForbiddenException('Admin permission required'); }
  async business(actorId:string,type:string,id:string,status:BusinessStatus){this.assertAdmin(type);if(status===BusinessStatus.ACTIVE){const f=await this.prisma.businessFiscalisation.findUnique({where:{businessId:id}});if(!f||f.status!=='COMPLIANT'||!f.taxpayerActive||!f.deviceActive||!f.deviceRegistered||!f.receiptVerifiedAt||f.taxClearanceExpiresAt<=new Date())throw new BadRequestException('Business cannot be approved until tax registration, fiscal device, receipt and Tax Clearance Certificate checks pass');}const value=await this.prisma.business.update({where:{id},data:{status}});await this.audit(actorId,'business.moderate','Business',id,{status});return value;}
  async fiscalisation(actorId:string,type:string,businessId:string,data:{approved:boolean;taxpayerActive:boolean;deviceActive:boolean;deviceRegistered:boolean;receiptVerificationReference?:string;rejectionReason?:string;nextReviewAt?:string}){this.assertAdmin(type);const record=await this.prisma.businessFiscalisation.findUnique({where:{businessId}});if(!record)throw new BadRequestException('No compliance evidence submitted');const passed=data.approved&&data.taxpayerActive&&data.deviceActive&&data.deviceRegistered&&Boolean(data.receiptVerificationReference)&&record.taxClearanceExpiresAt>new Date();if(data.approved&&!passed)throw new BadRequestException('TIN, device registration/activity, validated receipt and current Tax Clearance Certificate must all pass');return this.prisma.$transaction(async tx=>{const updated=await tx.businessFiscalisation.update({where:{businessId},data:{status:passed?'COMPLIANT':'CHANGES_REQUIRED',taxpayerActive:data.taxpayerActive,deviceActive:data.deviceActive,deviceRegistered:data.deviceRegistered,receiptVerifiedAt:passed?new Date():null,receiptVerificationReference:passed?data.receiptVerificationReference:null,rejectionReason:passed?null:(data.rejectionReason||'Compliance corrections required'),reviewedById:actorId,reviewedAt:new Date(),nextReviewAt:data.nextReviewAt?new Date(data.nextReviewAt):null}});await tx.business.update({where:{id:businessId},data:{status:passed?'ACTIVE':'PENDING'}});await tx.auditLog.create({data:{actorId,businessId,action:'business.compliance.review',resource:'BusinessFiscalisation',resourceId:updated.id,metadata:{passed,taxpayerActive:data.taxpayerActive,deviceActive:data.deviceActive,deviceRegistered:data.deviceRegistered}}});return updated;});}
  async ad(actorId: string, type: string, id: string, status: AdStatus) { this.assertAdmin(type); const value = await this.prisma.advertisement.update({ where: { id }, data: { status } }); await this.audit(actorId, 'ad.moderate', 'Advertisement', id, { status }); return value; }
  async document(actorId: string, type: string, id: string, status: DocumentStatus) { this.assertAdmin(type); const value = await this.prisma.document.update({ where: { id }, data: { status, reviewedAt: new Date() } }); await this.audit(actorId, 'document.review', 'Document', id, { status }); return value; }
  async payout(actorId: string, type: string, id: string, status: PayoutStatus) { this.assertAdmin(type); const value = await this.prisma.payout.update({ where: { id }, data: { status, approvedById: status === 'APPROVED' ? actorId : undefined } }); await this.audit(actorId, 'payout.review', 'Payout', id, { status }); return value; }
  reports(type: string) { this.assertAdmin(type); return this.prisma.report.findMany({ where: { status: { in: [ReportStatus.OPEN, ReportStatus.INVESTIGATING] } }, orderBy: { createdAt: 'asc' } }); }
  async verification(actorId:string,type:string,id:string,level:VerificationLevel){this.assertAdmin(type);const value=await this.prisma.business.update({where:{id},data:{verificationLevel:level}});await this.audit(actorId,'business.verification','Business',id,{level});return value}
  async review(actorId:string,type:string,id:string,hidden:boolean){this.assertAdmin(type);const value=await this.prisma.review.update({where:{id},data:{hidden,moderatedAt:new Date()}});await this.audit(actorId,'review.moderate','Review',id,{hidden});return value}
  async dispute(actorId:string,type:string,id:string,status:DisputeStatus,resolution?:string){this.assertAdmin(type);const value=await this.prisma.dispute.update({where:{id},data:{status,resolution}});await this.audit(actorId,'dispute.resolve','Dispute',id,{status});return value}
  tickets(type:string){this.assertAdmin(type);return this.prisma.supportTicket.findMany({where:{status:{in:['OPEN','INVESTIGATING']}},orderBy:{createdAt:'asc'}})}
  private audit(actorId: string, action: string, resource: string, resourceId: string, metadata: object) { return this.prisma.auditLog.create({ data: { actorId, action, resource, resourceId, metadata } }); }
}
