import{BadRequestException,ForbiddenException,Injectable,NotFoundException}from'@nestjs/common';import{AccountType,BusinessRole,Prisma,SubscriptionPlan}from'@prisma/client';import{PrismaService}from'../prisma/prisma.service';import{JobsService}from'../jobs/jobs.service';
@Injectable()export class GrowthService{constructor(private readonly p:PrismaService,private readonly jobs:JobsService){}
async follow(userId:string,type:string,productId:string){this.customer(type);const product=await this.p.product.findFirst({where:{id:productId,status:'ACTIVE'}});if(!product)throw new NotFoundException('Product not found');return this.p.productFollow.upsert({where:{customerId_productId:{customerId:userId,productId}},create:{customerId:userId,productId,lastPrice:product.price},update:{notifyPriceDrop:true,notifyRestock:true}})}
async reserve(userId:string,type:string,productId:string,branchId:string,quantity:number,hours:number){this.customer(type);const delay=Math.min(hours,24)*3600000;const reservation=await this.p.$transaction(async tx=>{const inv=await tx.branchInventory.findUnique({where:{branchId_productId:{branchId,productId}}});if(!inv||inv.quantity-inv.reserved<quantity)throw new BadRequestException('Insufficient reservable stock');await tx.branchInventory.update({where:{id:inv.id},data:{reserved:{increment:quantity}}});return tx.reservation.create({data:{customerId:userId,productId,branchId,quantity,expiresAt:new Date(Date.now()+delay)}})},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});await this.jobs.reservationExpiry(reservation.id,delay);return reservation}
async wholesale(userId:string,businessId:string,d:{title:string;description:string;minimumOrder:number}){await this.member(userId,businessId,[BusinessRole.OWNER,BusinessRole.MANAGER]);return this.p.wholesaleOffer.create({data:{...d,sellerId:businessId}})}
async invite(userId:string,businessId:string,offerId:string,buyerId:string){await this.member(userId,businessId,[BusinessRole.OWNER,BusinessRole.MANAGER]);const offer=await this.p.wholesaleOffer.findFirst({where:{id:offerId,sellerId:businessId}});if(!offer)throw new NotFoundException('Offer not found');return this.p.wholesaleAccess.create({data:{offerId,buyerId,approvedAt:new Date()}})}
async wholesaleFor(userId:string,businessId:string){await this.member(userId,businessId);return this.p.wholesaleOffer.findMany({where:{active:true,access:{some:{buyerId:businessId,approvedAt:{not:null}}}},select:{id:true,title:true,description:true,minimumOrder:true,seller:{select:{name:true,verificationLevel:true}}}})}
async loyalty(userId:string,businessId:string,name:string,pointsPerDollar:number){await this.member(userId,businessId,[BusinessRole.OWNER,BusinessRole.MANAGER,BusinessRole.MARKETING]);return this.p.loyaltyProgram.create({data:{businessId,name,pointsPerDollar}})}
async currency(userId:string,businessId:string,currency:string){await this.member(userId,businessId,[BusinessRole.OWNER,BusinessRole.FINANCE]);return this.p.businessCurrency.upsert({where:{businessId_currency:{businessId,currency:currency.toUpperCase()}},create:{businessId,currency:currency.toUpperCase()},update:{active:true}})}
async price(userId:string,businessId:string,productId:string,currency:string,amount:number){await this.member(userId,businessId,[BusinessRole.OWNER,BusinessRole.MANAGER,BusinessRole.FINANCE]);const product=await this.p.product.findFirst({where:{id:productId,businessId}});if(!product)throw new NotFoundException('Product not found');const value=await this.p.productPrice.upsert({where:{productId_currency:{productId,currency:currency.toUpperCase()}},create:{productId,currency:currency.toUpperCase(),amount},update:{amount}});const followers=await this.p.productFollow.findMany({where:{productId,notifyPriceDrop:true,OR:[{lastPrice:null},{lastPrice:{gt:amount}}]}});await Promise.all(followers.map(f=>this.jobs.alert(f.customerId,'PRICE_DROP',productId)));await this.p.productFollow.updateMany({where:{productId},data:{lastPrice:amount}});return value}
async subscription(userId:string,businessId:string,plan:SubscriptionPlan){await this.member(userId,businessId,[BusinessRole.OWNER]);return this.p.businessSubscription.upsert({where:{businessId},create:{businessId,plan},update:{plan,status:'ACTIVE'}})}
async recordSearch(userId:string|undefined,q:string,category:string|undefined,city:string|undefined,province:string|undefined,resultCount:number){return this.p.searchEvent.create({data:{userId,query:q.toLowerCase().trim(),category,city,province,resultCount}})}
async insights(userId:string,businessId:string){await this.member(userId,businessId);const since=new Date(Date.now()-30*86400000);const[searches,ads,sales,branches]=await Promise.all([this.p.searchEvent.groupBy({by:['query','city'],where:{createdAt:{gte:since}},_count:true,orderBy:{_count:{query:'desc'}},take:20}),this.p.advertisement.findMany({where:{businessId},select:{id:true,title:true,status:true}}),this.p.order.groupBy({by:['currency'],where:{businessId,createdAt:{gte:since}},_sum:{total:true},_count:true}),this.p.sale.groupBy({by:['branchId','currency'],where:{branch:{businessId},createdAt:{gte:since}},_sum:{total:true},_count:true})]);return{periodDays:30,aggregatedDemand:searches,advertisements:ads,onlineSales:sales,branchSales:branches}}
async recommendations(userId:string){const[orders,searches]=await Promise.all([this.p.orderItem.findMany({where:{order:{customerId:userId}},select:{product:{select:{name:true}}},take:20}),this.p.searchEvent.findMany({where:{userId},orderBy:{createdAt:'desc'},take:20,select:{query:true}})]);const terms=[...orders.map(x=>x.product.name.split(' ')[0]),...searches.map(x=>x.query)].filter(Boolean);return this.p.product.findMany({where:{status:'ACTIVE',...(terms.length?{OR:terms.map(t=>({name:{contains:t,mode:'insensitive'}}))}:{})},select:{id:true,name:true,slug:true,price:true,prices:true,business:{select:{name:true,slug:true}}},orderBy:{createdAt:'desc'},take:20})}
async search(userId:string,type:string,q:string,city?:string,province?:string){this.customer(type);const products=await this.p.product.findMany({where:{status:'ACTIVE',name:{contains:q,mode:'insensitive'},business:{status:'ACTIVE',branches:{some:{...(city?{city:{equals:city,mode:'insensitive'}}:{}),...(province?{province:{equals:province,mode:'insensitive'}}:{})}}}},select:{id:true,name:true,slug:true,description:true,price:true,prices:true,business:{select:{name:true,slug:true,verificationLevel:true,branches:{select:{city:true,province:true,deliveryAreas:true}}}}},take:50});await this.recordSearch(userId,q,undefined,city,province,products.length);return products}
async voucher(userId:string,businessId:string,programId:string,code:string,discountPercent:number,expiresAt:Date){await this.member(userId,businessId,[BusinessRole.OWNER,BusinessRole.MANAGER,BusinessRole.MARKETING]);const program=await this.p.loyaltyProgram.findFirst({where:{id:programId,businessId}});if(!program)throw new NotFoundException('Loyalty program not found');return this.p.voucher.create({data:{programId,code,discountPercent,expiresAt}})}
async referral(userId:string,programId:string,rewardPoints:number){const program=await this.p.loyaltyProgram.findUnique({where:{id:programId}});if(!program)throw new NotFoundException('Program not found');return this.p.referral.create({data:{programId,referrerId:userId,rewardPoints,code:crypto.randomUUID().slice(0,8).toUpperCase()}})}async claimReferral(userId:string,code:string){const referral=await this.p.referral.findFirst({where:{code,claimedAt:null,referredId:null}});if(!referral||referral.referrerId===userId)throw new BadRequestException('Invalid referral');return this.p.$transaction(async tx=>{await tx.referral.update({where:{id:referral.id},data:{referredId:userId,claimedAt:new Date()}});await tx.loyaltyAccount.upsert({where:{programId_customerId:{programId:referral.programId,customerId:referral.referrerId}},create:{programId:referral.programId,customerId:referral.referrerId,points:referral.rewardPoints},update:{points:{increment:referral.rewardPoints}}});return{claimed:true}})}
private customer(type:string){if(type!==AccountType.CUSTOMER)throw new ForbiddenException('Customer account required')}private async member(userId:string,businessId:string,roles?:BusinessRole[]){const m=await this.p.businessMember.findUnique({where:{userId_businessId:{userId,businessId}}});if(!m)throw new NotFoundException('Business not found');if(roles&&!roles.includes(m.role))throw new ForbiddenException('Insufficient permission');return m}}
