'use client';
import Link from 'next/link';
import { use, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, BadgeCheck, CalendarDays, Clock, CreditCard, Heart, LoaderCircle, MapPin, MessageSquare, Minus, Plus, ShoppingBag, Sparkles, Star, Store, Truck } from 'lucide-react';
import { api, MarketplaceService, Order, savedSession, Shop } from '../../../src/api';
import './shop.css';

export default function ShopPage({params}:{params:Promise<{slug:string}>}){
 const{slug}=use(params);const[shop,setShop]=useState<Shop|null>(null);const[services,setServices]=useState<MarketplaceService[]>([]);const[error,setError]=useState('');const[placing,setPlacing]=useState(false);const[done,setDone]=useState('');const[cart,setCart]=useState<Record<string,number>>({});const[order,setOrder]=useState<Order|null>(null);const[provider,setProvider]=useState('MOBILE_MONEY');const[following,setFollowing]=useState(false);
 useEffect(()=>{const session=savedSession();if(!session){location.href=`/login/customer?next=${encodeURIComponent(`/shops/${slug}`)}`;return}api.shop(slug,session.accessToken).then(value=>{setShop(value);setServices(value.services||[])}).catch(reason=>setError(reason instanceof Error?reason.message:'Shop could not be loaded'))},[slug]);
 const count=Object.values(cart).reduce((a,b)=>a+b,0);const total=useMemo(()=>shop?.products.reduce((sum,p)=>sum+Number(p.price)*(cart[p.id]||0),0)||0,[shop,cart]);
 function quantity(id:string,delta:number){setCart(current=>({...current,[id]:Math.max(0,Math.min(99,(current[id]||0)+delta))}))}
 async function purchase(){const session=savedSession();if(!session){location.href='/login/customer';return}if(session.user.accountType!=='CUSTOMER'){setError('Please use a customer account to make purchases.');return}setPlacing(true);setError('');try{const created=await api.createOrder(session.accessToken,Object.entries(cart).filter(([,q])=>q>0).map(([productId,quantity])=>({productId,quantity})));setOrder(created);setCart({});setDone('Order created. Choose a payment method to complete checkout.')}catch(reason){setError(reason instanceof Error?reason.message:'Order could not be placed')}finally{setPlacing(false)}}
 async function pay(){const session=savedSession();if(!session||!order)return;setPlacing(true);setError('');try{const payment=await api.payOrder(session.accessToken,order.id,provider);await api.completeDemoPayment(session.accessToken,payment.id);setOrder(null);setDone('Payment completed successfully. Your order is confirmed.')}catch(reason){setError(reason instanceof Error?reason.message:'Payment could not be completed')}finally{setPlacing(false)}}
 async function book(service:MarketplaceService){const session=savedSession();if(!session){location.href='/login/customer';return}const value=prompt('Choose appointment date and time (example: 2026-08-25T10:00)','');if(!value)return;const startsAt=new Date(value);if(Number.isNaN(startsAt.getTime())){setError('Enter a valid appointment date and time.');return}setPlacing(true);try{await api.createBooking(session.accessToken,{serviceId:service.id,startsAt:startsAt.toISOString()});setDone(`${service.name} booked. The provider will confirm the appointment and payment details.`)}catch(reason){setError(reason instanceof Error?reason.message:'Service could not be booked')}finally{setPlacing(false)}}
 async function contact(){const session=savedSession();if(!session||!shop)return;try{const conversation=await api.openConversation(session.accessToken,{businessId:shop.id});location.href=`/dashboard?conversation=${conversation.id}`}catch(reason){setError(reason instanceof Error?reason.message:'Conversation could not be opened')}}
 if(error&&!shop)return <main className="shop-state"><Store/><h1>{error}</h1><Link href="/marketplace">Browse other shops</Link></main>;
 if(!shop)return <main className="shop-state"><LoaderCircle className="spin"/><p>Opening shop…</p></main>;
 const branch=shop.branches[0];
 return <main className="shop-page"><header><Link className="brand" href="/marketplace"><span className="brand-mark">Z</span><span>ZimMarket</span></Link><Link href="/dashboard">My account</Link></header>
 <section className="shop-hero"><Link href="/marketplace"><ArrowLeft/> All shops</Link><div><span className="shop-avatar"><Store/></span><div><small>{shop.industry||'LOCAL BUSINESS'}</small><h1>{shop.name} <BadgeCheck/></h1><p><MapPin/> {branch?.city||'Zimbabwe'} · {shop.verificationLevel.toLowerCase()} verified · <Star/> {shop.rating?.average?.toFixed(1)||'New'} ({shop.rating?.count||0})</p></div></div></section>
 <section className="storefront-toolbar"><div><span><Clock/> {branch?.operatingHours?Object.entries(branch.operatingHours as object).map(([day,hours])=>`${day}: ${hours}`).join(' · '):'Contact store for opening hours'}</span><span><Truck/> Delivery: {branch?.deliveryAreas?.join(', ')||'Confirm with store'}</span></div><div><button onClick={contact}><MessageSquare/> Contact</button><button onClick={()=>setFollowing(value=>!value)}><Heart fill={following?'currentColor':'none'}/> {following?'Following':'Follow business'}</button><button onClick={()=>location.href='/dashboard'}>Request quotation</button></div></section>
 <section className="storefront-tags">{(shop.communityTags||[]).map(tag=><span key={tag}>{tag}</span>)}{shop.industry&&<span>{shop.industry}</span>}</section>
 {(shop.ads||[]).length>0&&<section className="store-promotions"><Sparkles/><div><small>CURRENT PROMOTIONS</small>{shop.ads?.map(ad=><b key={ad.id}>{ad.title}</b>)}</div></section>}
 <section className="shop-catalog"><div className="shop-heading"><div><span>SHOP THE COLLECTION</span><h2>Available products</h2></div><b>{shop.products.length} item{shop.products.length===1?'':'s'}</b></div>{done&&<div className="shop-success">{done} <Link href="/dashboard">View account</Link></div>}{error&&<div className="login-error">{error}</div>}{order&&<div className="payment-step"><CreditCard/><div><small>FINAL STEP</small><h3>Pay {order.currency} {Number(order.total).toFixed(2)}</h3><p>Select how you would like to complete this order.</p></div><select value={provider} onChange={event=>setProvider(event.target.value)}><option value="MOBILE_MONEY">Mobile money</option><option value="CARD">Bank card</option><option value="BANK_TRANSFER">Bank transfer</option><option value="CASH_ON_DELIVERY">Cash on delivery</option></select><button onClick={pay} disabled={placing}>{placing?'Processing…':'Complete payment'}</button></div>}
 <div className="shop-products">{shop.products.map((product,index)=><article key={product.id}><div className={`shop-product-art tone-${index%4}`}><ShoppingBag/></div><small>{shop.name}</small><h3>{product.name}</h3><p>{product.description||'Available from this trusted local shop.'}</p><div className="shop-product-bottom"><strong>US${Number(product.price).toFixed(2)}</strong>{cart[product.id]?<span className="quantity"><button onClick={()=>quantity(product.id,-1)}><Minus/></button><b>{cart[product.id]}</b><button onClick={()=>quantity(product.id,1)}><Plus/></button></span>:<button className="add-button" onClick={()=>quantity(product.id,1)}>Add to cart</button>}</div></article>)}</div>{!shop.products.length&&<div className="shop-empty">This shop has no products available yet.</div>}
 {services.length>0&&<div className="shop-services"><div className="shop-heading"><div><span>BOOK AN APPOINTMENT</span><h2>Available services</h2></div><b>{services.length} service{services.length===1?'':'s'}</b></div><div>{services.map(service=><article key={service.id}><Sparkles/><div><small>{service.category}</small><h3>{service.name}</h3><p>{service.description||`Professional service from ${shop.name}.`}</p><b>{service.durationMinutes} min · {service.price?`${service.currency||'USD'} ${Number(service.price).toFixed(2)}`:'Ask for price'} · appointment times available on request</b></div><button onClick={()=>book(service)} disabled={placing}><CalendarDays/> Book service</button></article>)}</div></div>}
 <section className="store-reviews"><div className="shop-heading"><div><span>VERIFIED CUSTOMERS</span><h2>Customer reviews</h2></div><b>{shop.rating?.count||0} review{shop.rating?.count===1?'':'s'}</b></div><div>{shop.reviews?.map(review=><article key={review.id}><Star/><div><b>{review.customer.fullName||'Verified customer'} · {review.rating}/5</b><p>{review.comment||'Verified purchase rating'}</p><small>{new Date(review.createdAt).toLocaleDateString()}</small></div></article>)}{!shop.reviews?.length&&<div className="shop-empty">No customer reviews yet. Reviews can be left after a completed purchase.</div>}</div></section>
 </section>{count>0&&!order&&<aside className="cart-bar"><div><span>{count} item{count===1?'':'s'} selected</span><strong>US${total.toFixed(2)}</strong></div><button onClick={purchase} disabled={placing}>{placing?<LoaderCircle className="spin"/>:<ShoppingBag/>}{placing?'Creating order…':'Continue to payment'}</button></aside>}</main>;
}
